from typing import List, Union

def geometricMean(values: List[Union[float, int, long]]) -> float: ...
def kurtosis(values: List[Union[float, int, long]]) -> float: ...
def max(values: List[Union[float, int, long]]) -> float: ...
def mean(values: List[Union[float, int, long]]) -> float: ...
def meanDifference(
    values1: List[Union[float, int, long]], values2: List[Union[float, int, long]]
) -> float: ...
def median(values: List[Union[float, int, long]]) -> float: ...
def min(values: List[Union[float, int, long]]) -> float: ...
def mode(values: List[Union[float, int, long]]) -> List[float]: ...
def normalize(values: List[Union[float, int, long]]) -> List[float]: ...
def percentile(values: List[Union[float, int, long]], percentile: float) -> float: ...
def populationVariance(values: List[Union[float, int, long]]) -> float: ...
def product(values: List[Union[float, int, long]]) -> float: ...
def skewness(values: List[Union[float, int, long]]) -> float: ...
def standardDeviation(values: List[Union[float, int, long]]) -> float: ...
def sum(values: List[Union[float, int, long]]) -> float: ...
def sumDifference(
    values1: List[Union[float, int, long]], values2: List[Union[float, int, long]]
) -> float: ...
def sumLog(values: List[Union[float, int, long]]) -> float: ...
def sumSquares(values: List[Union[float, int, long]]) -> float: ...
def variance(values: List[Union[float, int, long]]) -> float: ...
