from typing import Any, Dict, Optional, Union

from com.inductiveautomation.factorypmi.application import FPMIWindow
from com.inductiveautomation.factorypmi.application.script.builtin import NavUtilities
from java.util import EventObject

def centerWindow(arg: Union[str, unicode, FPMIWindow]) -> None: ...
def closeParentWindow(event: EventObject) -> None: ...
def closeWindow(arg: Union[str, unicode, FPMIWindow]) -> None: ...
def desktop(handle: Union[str, unicode, None] = ...) -> NavUtilities: ...
def getCurrentWindow() -> Union[str, unicode]: ...
def goBack() -> FPMIWindow: ...
def goForward() -> FPMIWindow: ...
def goHome() -> FPMIWindow: ...
def openWindow(
    path: Union[str, unicode], params: Optional[Dict[Union[str, unicode], Any]] = ...
) -> FPMIWindow: ...
def openWindowInstance(
    path: Union[str, unicode], params: Optional[Dict[Union[str, unicode], Any]] = ...
) -> FPMIWindow: ...
def swapTo(
    path: Union[str, unicode], params: Optional[Dict[Union[str, unicode], Any]] = ...
) -> FPMIWindow: ...
def swapWindow(
    arg: Union[str, unicode, EventObject],
    swapToPath: Union[str, unicode],
    params: Optional[Dict[Union[str, unicode], Any]] = ...,
) -> FPMIWindow: ...
