from typing import Optional, Tuple, Union

from java.util import EventObject

def getRoles() -> Tuple[Union[str, unicode], ...]: ...
def getUserRoles(
    username: Union[str, unicode],
    password: Union[str, unicode],
    authProfile: Union[str, unicode] = ...,
    timeout: int = ...,
) -> Optional[Tuple[Union[str, unicode], ...]]: ...
def getUsername() -> Union[str, unicode]: ...
def isScreenLocked() -> bool: ...
def lockScreen(obscure: bool = ...) -> None: ...
def logout() -> None: ...
def switchUser(
    username: Union[str, unicode],
    password: Union[str, unicode],
    event: EventObject,
    hideError: bool = ...,
) -> bool: ...
def unlockScreen() -> None: ...
def validateUser(
    username: Union[str, unicode],
    password: Union[str, unicode],
    authProfile: Union[str, unicode] = ...,
    timeout: int = ...,
) -> bool: ...
