from typing import Any, Dict, Union

from com.inductiveautomation.ignition.common import BasicDataset
from com.inductiveautomation.sfc.api import PyChartScope

def cancelChart(instanceId: Union[str, unicode]) -> None: ...
def getRunningCharts(chartPath: Union[str, unicode, None] = ...) -> BasicDataset: ...
def getVariables(instanceId: Union[str, unicode]) -> PyChartScope: ...
def pauseChart(instanceId: Union[str, unicode]) -> None: ...
def redundantCheckpoint(instanceId: Union[str, unicode]) -> None: ...
def resumeChart(instanceId: Union[str, unicode]) -> None: ...
def setVariable(
    instanceId: Union[str, unicode],
    stepId: Union[str, unicode],
    variableName: Union[str, unicode],
    variableValue: Any,
) -> None: ...
def setVariables(
    instanceId: Union[str, unicode],
    stepId: Union[str, unicode],
    variableMap: Dict[Union[str, unicode], Any],
) -> None: ...
def startChart(
    projectName: Union[str, unicode],
    chartPath: Union[str, unicode],
    arguments: Dict[Union[str, unicode], Any],
) -> Union[str, unicode]: ...
