from typing import List, Optional, Union

from com.inductiveautomation.ignition.common.messages import UIResponse
from com.inductiveautomation.ignition.common.user import PyUser, UserSourceMeta
from com.inductiveautomation.ignition.common.user.schedule import (
    AbstractScheduleModel,
    HolidayModel,
    ScheduleAdjustment,
)
from java.util import Date

def addCompositeSchedule(
    name: Union[str, unicode],
    scheduleOne: Union[str, unicode],
    scheduleTwo: Union[str, unicode],
    description: Union[str, unicode, None] = ...,
) -> UIResponse: ...
def addHoliday(holiday: HolidayModel) -> UIResponse: ...
def addRole(
    userSource: Union[str, unicode], role: Union[str, unicode]
) -> UIResponse: ...
def addSchedule(schedule: AbstractScheduleModel) -> UIResponse: ...
def addUser(userSource: Union[str, unicode], user: PyUser) -> UIResponse: ...
def createScheduleAdjustment(
    startDate: Date, endDate: Date, isAvailable: bool, note: Union[str, unicode]
) -> ScheduleAdjustment: ...
def editHoliday(
    holidayName: Union[str, unicode], holiday: HolidayModel
) -> UIResponse: ...
def editRole(
    userSource: Union[str, unicode],
    oldName: Union[str, unicode],
    newName: Union[str, unicode],
) -> UIResponse: ...
def editSchedule(
    scheduleName: Union[str, unicode], schedule: AbstractScheduleModel
) -> UIResponse: ...
def editUser(userSource: Union[str, unicode], user: PyUser) -> UIResponse: ...
def getHoliday(holidayName: Union[str, unicode]) -> Optional[HolidayModel]: ...
def getHolidayNames() -> List[Union[str, unicode]]: ...
def getHolidays() -> List[HolidayModel]: ...
def getNewUser(
    userSource: Union[str, unicode], username: Union[str, unicode]
) -> PyUser: ...
def getRoles(userSource: Union[str, unicode]) -> List[Union[str, unicode]]: ...
def getSchedule(
    scheduleName: Union[str, unicode],
) -> Optional[AbstractScheduleModel]: ...
def getScheduleNames() -> List[Union[str, unicode]]: ...
def getScheduledUsers(
    userSource: Union[str, unicode], date: Union[Date, int] = ...
) -> List[PyUser]: ...
def getSchedules() -> List[AbstractScheduleModel]: ...
def getUser(
    userSource: Union[str, unicode], username: Union[str, unicode]
) -> PyUser: ...
def getUserSources() -> List[UserSourceMeta]: ...
def getUsers(userSource: Union[str, unicode]) -> List[PyUser]: ...
def isUserScheduled(user: PyUser, date: Optional[Union[Date, int]] = ...) -> bool: ...
def removeHoliday(holidayName: Union[str, unicode]) -> UIResponse: ...
def removeRole(
    userSource: Union[str, unicode], role: Union[str, unicode]
) -> UIResponse: ...
def removeSchedule(scheduleName: Union[str, unicode]) -> UIResponse: ...
def removeUser(
    userSource: Union[str, unicode], username: Union[str, unicode]
) -> UIResponse: ...
