from typing import Iterable, List, Union

from java.lang import Enum, Object
from java.util import Date

class LicenseDetails:
    def checkFlag(self, key: Union[str, unicode]) -> bool: ...
    def getExpirationDate(self) -> Date: ...
    def getLicenseDetail(self, key: Union[str, unicode]) -> Union[str, unicode]: ...
    def getLicenseDetails(
        self, key: Union[str, unicode]
    ) -> List[LicenseRestriction]: ...
    def getModuleId(self) -> Union[str, unicode]: ...
    def getVersion(self) -> int: ...
    def isPlatformDetails(self) -> bool: ...

class LicenseState:
    def getLicenseMode(self) -> LicenseMode: ...
    def getModuleLicense(self) -> ModuleLicense: ...
    def getPlatformLicense(self) -> LicenseDetails: ...
    def getTrialExpirationDate(self) -> Date: ...
    def isTrialExpired(self) -> bool: ...

class LicenseMode(Enum):
    @staticmethod
    def values() -> Iterable[LicenseMode]: ...

class LicenseRestriction(Object):
    def __init__(
        self,
        restrictionName: Union[str, unicode],
        restrictionValue: Union[str, unicode],
    ) -> None: ...
    def getrestrictionName(self) -> Union[str, unicode]: ...
    def getrestrictionValue(self) -> Union[str, unicode]: ...

class ModuleLicense(LicenseDetails):
    def getLicenseDetail(self, key: Union[str, unicode]) -> Union[str, unicode]: ...
    def getLicenseDetails(
        self, key: Union[str, unicode]
    ) -> List[LicenseRestriction]: ...
    def getModuleId(self) -> Union[str, unicode]: ...
    def getVersion(self) -> int: ...
