from typing import Union

from java.lang import Object
from javax.security.auth import Subject

class Principal:
    def equals(self, another: Object) -> bool: ...
    def getName(self) -> Union[str, unicode]: ...
    def hashCode(self) -> int: ...
    def implies(self, subject: Subject) -> bool: ...
    def toString(self) -> Union[str, unicode]: ...
