from typing import Iterable, List, Union

from com.inductiveautomation.ignition.common.util import Timeline
from com.palantir.ptoss.cinch.core import DefaultBindableModel
from java.lang import Enum
from java.util import Calendar, Date

class AbstractScheduleModel(DefaultBindableModel):
    def __init__(self) -> None: ...
    def getDescription(self) -> Union[str, unicode]: ...
    def getName(self) -> Union[str, unicode]: ...
    def getScheduleForDay(self, cal: Calendar) -> Timeline: ...
    def getType(self) -> Union[str, unicode]: ...
    def isObserveHolidays(self) -> bool: ...
    def setDescription(self, description: Union[str, unicode]) -> None: ...
    def setName(self, name: Union[str, unicode]) -> None: ...
    def setObserveHolidays(self, observeHolidays: bool) -> None: ...

class BasicScheduleModel(AbstractScheduleModel):
    def __init__(self) -> None: ...
    def getAllDayTime(self) -> Union[str, unicode]: ...
    def getFridayTime(self) -> Union[str, unicode]: ...
    def getMondayTime(self) -> Union[str, unicode]: ...
    def getRepeat(self) -> ScheduleRepeatStyle: ...
    def getRepeatOff(self) -> int: ...
    def getRepeatOn(self) -> int: ...
    def getSaturdayTime(self) -> Union[str, unicode]: ...
    def getScheduleForDay(self, cal: Calendar) -> Timeline: ...
    def getStartingAt(self) -> Date: ...
    def getSundayTime(self) -> Union[str, unicode]: ...
    def getThursdayTime(self) -> Union[str, unicode]: ...
    def getTuesdayTime(self) -> Union[str, unicode]: ...
    def getWednesdayTime(self) -> Union[str, unicode]: ...
    def getWeekDayTime(self) -> Union[str, unicode]: ...
    def isAllDays(self) -> bool: ...
    def isFriday(self) -> bool: ...
    def isMonday(self) -> bool: ...
    def isObserveHolidays(self) -> bool: ...
    def isRepeating(self) -> bool: ...
    def isSaturday(self) -> bool: ...
    def isSunday(self) -> bool: ...
    def isThursday(self) -> bool: ...
    def isTuesday(self) -> bool: ...
    def isUseDays(self) -> bool: ...
    def isWednesday(self) -> bool: ...
    def isWeekDays(self) -> bool: ...
    def set(self, that: BasicScheduleModel) -> None: ...
    def setAllDays(self, allDays: bool) -> None: ...
    def setAllDayTime(self, allDayTime: Union[str, unicode]) -> None: ...
    def setFriday(self, friday: bool) -> None: ...
    def setFridayTime(self, fridayTime: Union[str, unicode]) -> None: ...
    def setMonday(self, monday: bool) -> None: ...
    def setMondayTime(self, mondayTime: Union[str, unicode]) -> None: ...
    def setObserveHolidays(self, observeHolidays: bool) -> None: ...
    def setRepeat(self, repeat: ScheduleRepeatStyle) -> None: ...
    def setRepeatOff(self, repeatOff: int) -> None: ...
    def setRepeatOn(self, repeatOn: int) -> None: ...
    def setSaturday(self, saturday: bool) -> None: ...
    def setSaturdayTime(self, saturdayTime: Union[str, unicode]) -> None: ...
    def setStartingAt(self, startingAt: Date) -> None: ...
    def setSunday(self, sunday: bool) -> None: ...
    def setSundayTime(self, sundayTime: Union[str, unicode]) -> None: ...
    def setThursday(self, thursday: bool) -> None: ...
    def setThursdayTime(self, thursdayTime: Union[str, unicode]) -> None: ...
    def setTuesday(self, tuesday: bool) -> None: ...
    def setTuesdayTime(self, tuesdayTime: Union[str, unicode]) -> None: ...
    def setWednesday(self, wednesday: bool) -> None: ...
    def setWednesdayTime(self, wednesdayTime: Union[str, unicode]) -> None: ...
    def setWeekDays(self, weekDays: bool) -> None: ...
    def setWeekDayTime(self, weekDayTime: Union[str, unicode]) -> None: ...

class CompositeScheduleModel(AbstractScheduleModel):
    def __init__(self, models: List[AbstractScheduleModel]) -> None: ...
    def getModels(self) -> List[AbstractScheduleModel]: ...
    def getScheduleForDay(self, cal: Calendar) -> Timeline: ...
    def isObserveHolidays(self) -> bool: ...
    def setObserveHolidays(self, observeHolidays: bool) -> None: ...

class HolidayModel(DefaultBindableModel):
    date: Date
    name: Union[str, unicode]
    repeatAnnually: bool
    def __init__(
        self, name: Union[str, unicode], date: Date, repeatAnnually: bool
    ) -> None: ...
    def getDate(self) -> Date: ...
    def getName(self) -> Union[str, unicode]: ...
    def isRepeatAnnually(self) -> bool: ...
    def set(self, that: HolidayModel) -> None: ...
    def setDate(self, date: Date) -> None: ...
    def setName(self, name: Union[str, unicode]) -> None: ...
    def setRepeatAnnually(self, repeatAnnually: bool) -> None: ...

class ScheduleAdjustment(DefaultBindableModel):
    start: Date
    end: Date
    available: bool
    note: Union[str, unicode]
    def __init__(
        self, start: Date, end: Date, available: bool, note: Union[str, unicode]
    ) -> None: ...
    def contains(self, timestamp: long) -> bool: ...
    def getEnd(self) -> Date: ...
    def getNote(self) -> Union[str, unicode]: ...
    def getStart(self) -> Date: ...
    def isAvailable(self) -> bool: ...
    def setAvailable(self, available: bool) -> None: ...
    def setEnd(self, end: Date) -> None: ...
    def setNote(self, note: Union[str, unicode]) -> None: ...
    def setStart(self, start: Date) -> None: ...

class ScheduleRepeatStyle(Enum):
    @staticmethod
    def values() -> Iterable[ScheduleRepeatStyle]: ...
