from typing import Any, Iterator, List, Optional, Union

from java.io import Writer
from java.lang import Number, Object

class JSONArray(Object):
    def __init__(self, arg: Any = ...) -> None: ...
    def get(self, index: int) -> Object: ...
    def getBoolean(self, index: int) -> bool: ...
    def getDouble(self, index: int) -> float: ...
    def getInt(self, index: int) -> int: ...
    def getJSONArray(self, index: int) -> JSONArray: ...
    def getJSONObject(self, index: int) -> JSONObject: ...
    def getLong(self, index: int) -> long: ...
    def getString(self, index: int) -> Union[str, unicode]: ...
    def isNull(self, index: int) -> bool: ...
    def join(self, separator: Union[str, unicode]) -> Union[str, unicode]: ...
    def length(self) -> int: ...
    def opt(self, index: int) -> Object: ...
    def optBoolean(self, index: int, defaultValue: Optional[bool] = ...) -> bool: ...
    def optDouble(self, index: int, defaultValue: Optional[float] = ...) -> float: ...
    def optInt(self, index: int, defaultValue: Optional[int] = ...) -> int: ...
    def optJSONArray(self, index: int) -> JSONArray: ...
    def optJSONObject(self, index: int) -> JSONObject: ...
    def optLong(self, index: int, defaultValue: Optional[long] = ...) -> long: ...
    def optString(
        self, index: int, defaultValue: Union[str, unicode, None] = ...
    ) -> Union[str, unicode]: ...
    def put(self, index: int, value: Any) -> JSONArray: ...
    def remove(self, index: int) -> Object: ...
    def toJSONObject(self, names: JSONArray) -> JSONObject: ...
    def toString(self, indentFactor: Optional[int] = ...) -> Union[str, unicode]: ...
    def write(self, writer: Writer) -> Writer: ...

class JSONObject(Object):
    NULL: Object
    def __init__(self, *args: Any) -> None: ...
    def accumulate(self, key: Union[str, unicode], value: Object) -> JSONObject: ...
    def append(self, key: Union[str, unicode], value: Object) -> JSONObject: ...
    @staticmethod
    def doubleToString(d: float) -> Union[str, unicode]: ...
    def get(self, key: Union[str, unicode]) -> Object: ...
    def getBoolean(self, key: Union[str, unicode]) -> bool: ...
    def getDouble(self, key: Union[str, unicode]) -> float: ...
    def getInt(self, key: Union[str, unicode]) -> int: ...
    def getJSONArray(self, key: Union[str, unicode]) -> JSONArray: ...
    def getJSONObject(self, key: Union[str, unicode]) -> JSONObject: ...
    def getLong(self, key: Union[str, unicode]) -> long: ...
    @staticmethod
    def getNames(arg: JSONObject) -> List[Union[str, unicode]]: ...
    def getString(self, key: Union[str, unicode]) -> Union[str, unicode]: ...
    def has(self, key: Union[str, unicode]) -> bool: ...
    def increment(self, key: Union[str, unicode]) -> JSONObject: ...
    def isNull(self, key: Union[str, unicode]) -> bool: ...
    def keys(self) -> Iterator[Union[str, unicode]]: ...
    def length(self) -> int: ...
    def names(self) -> JSONArray: ...
    @staticmethod
    def numberToString(n: Number) -> Union[str, unicode]: ...
    def opt(self, key: Union[str, unicode]) -> Object: ...
    def optBoolean(
        self, key: Union[str, unicode], defaultValue: Optional[bool] = ...
    ) -> bool: ...
    def optDouble(
        self, key: Union[str, unicode], defaultValue: Optional[float] = ...
    ) -> float: ...
    def optInt(
        self, key: Union[str, unicode], defaultValue: Optional[int] = ...
    ) -> int: ...
    def optJSONArray(self, key: Union[str, unicode]) -> JSONArray: ...
    def optJSONObject(self, key: Union[str, unicode]) -> JSONObject: ...
    def optLong(
        self, key: Union[str, unicode], defaultValue: Optional[long] = ...
    ) -> long: ...
    def optString(
        self, key: Union[str, unicode], defaultValue: Union[str, unicode, None] = ...
    ) -> Union[str, unicode]: ...
    def put(self, key: Union[str, unicode], value: Any) -> JSONObject: ...
    def putOnce(self, key: Union[str, unicode], value: Object) -> JSONObject: ...
    def putOpt(self, key: Union[str, unicode], value: Object) -> JSONObject: ...
    @staticmethod
    def quote(string: Union[str, unicode]) -> Union[str, unicode]: ...
    def remove(self, key: Union[str, unicode]) -> Object: ...
    def sortedKeys(self) -> Iterator[Union[str, unicode]]: ...
    @staticmethod
    def stringToValue(s: Union[str, unicode]) -> Object: ...
    def toJSONArray(self, names: JSONArray) -> JSONArray: ...
    def toString(self, indentFactor: Optional[int] = ...) -> Union[str, unicode]: ...
    @staticmethod
    def valueToString(value: Object) -> Union[str, unicode]: ...
    @staticmethod
    def wrap(obj: Object) -> Object: ...
    def write(self, writer: Writer) -> Writer: ...
