from typing import Any, Iterable, Set, Union

from com.inductiveautomation.ignition.common.binding import InteractionListener
from com.inductiveautomation.ignition.common.expressions.functions import Function
from com.inductiveautomation.ignition.common.model.values import QualifiedValue
from java.lang import Class

class Expression:
    def connect(self, context: Any, updateListener: InteractionListener) -> None: ...
    def disconnect(self) -> None: ...
    def execute(self, args: Iterable[Expression]) -> QualifiedValue: ...
    def getChildren(self) -> Iterable[Expression]: ...
    def getOpName(self) -> Union[str, unicode]: ...
    def getType(self) -> Class: ...
    def shutdown(self) -> None: ...
    def startup(self) -> None: ...

class FunctionFactory:
    def getCategories(self) -> Set[Union[str, unicode]]: ...
    def getFunction(self, name: Union[str, unicode]) -> Function: ...
    def getFunctionNames(self) -> Set[Union[str, unicode]]: ...
    def getFunctionsInCategory(
        self, name: Union[str, unicode]
    ) -> Set[Union[str, unicode]]: ...
