from typing import Any, Set, Union

from java.lang import Class, Object
from java.util import Collection, Date, Map
from org.bson.codecs.configuration import CodecRegistry
from org.bson.types import ObjectId

class BSONObject:
    def containsField(self, s: Union[str, unicode]) -> bool: ...
    def get(self, key: Union[str, unicode]) -> Object: ...
    def keySet(self) -> Set[Union[str, unicode]]: ...
    def put(self, k: Union[str, unicode], v: Object) -> Object: ...
    def putAll(self, arg: Union[BSONObject, Map]) -> None: ...
    def removeField(self, key: Union[str, unicode]) -> Object: ...
    def toMap(self) -> Map: ...

class BsonValue(Object):
    def __init__(self) -> None: ...

class BsonDocument(BsonValue):
    def __init__(self, *args: Any) -> None: ...

class Document(Object):
    def __init__(self, *args: Any) -> None: ...
    def append(self, key: Union[str, unicode], value: Object) -> Document: ...
    def clear(self) -> None: ...
    def containsKey(self, key: Object) -> bool: ...
    def containsValue(self, value: Object) -> bool: ...
    def entrySet(self) -> Set[Any]: ...
    def get(self, *args: Any) -> Any: ...
    def getBoolean(self, *args: Any) -> bool: ...
    def getDate(self, key: Object) -> Date: ...
    def getDouble(self, key: Object) -> float: ...
    def getInteger(self, key: Object) -> int: ...
    def getLong(self, key: Object) -> long: ...
    def getObjectId(self, key: Object) -> ObjectId: ...
    def getString(self, key: Object) -> Union[str, unicode]: ...
    def isEmpty(self) -> bool: ...
    def keySet(self) -> Set[Union[str, unicode]]: ...
    @staticmethod
    def parse(*args: Any) -> Document: ...
    def put(self, key: Union[str, unicode], value: Object) -> Object: ...
    def putAll(self, map: Map) -> None: ...
    def remove(self, key: Object) -> Object: ...
    def size(self) -> int: ...
    def toBsonDocument(
        self, documentClass: Class, codecRegistry: CodecRegistry
    ) -> BsonDocument: ...
    def toJson(self, *args: Any) -> Union[str, unicode]: ...
    def values(self) -> Collection: ...
