from typing import Any, Iterable, List, Mapping, Optional, Union

from com.inductiveautomation.ignition.common.xmlserialization import (
    ClassNameResolver,
    SerializationException,
)
from com.inductiveautomation.ignition.common.xmlserialization.serialization import (
    XMLSerializer,
)
from java.io import InputStream, Reader
from java.lang import Class, Object

class AttributesMap:
    def getClass(self, name: Union[str, unicode]) -> Class: ...
    def getDecoder(self, name: Union[str, unicode]) -> Any: ...
    def getInt(self, name: Union[str, unicode]) -> int: ...
    def getLength(self) -> int: ...
    def getName(self, index: int) -> Union[str, unicode]: ...
    def getSignature(self, name: Union[str, unicode]) -> Iterable[Class]: ...
    def getAnyStr(self, name: Union[str, unicode]) -> Union[str, unicode]: ...
    def getValue(self, name: Union[str, unicode], decoder: Any) -> Any: ...

class DeserializationContext:
    def getClassNameMap(self) -> ClassNameResolver: ...
    def getRootAttributes(
        self,
    ) -> Mapping[Union[str, unicode], Union[str, unicode]]: ...
    def getRootObjects(self) -> List[Object]: ...
    def getWarnings(self) -> List[SerializationException]: ...

class DeserializationHandler:
    def clone(self) -> DeserializationHandler: ...
    def endElement(self, context: DeserializationContext) -> None: ...
    def endObject(self, obj: Object) -> None: ...
    def endSubElement(
        self, name: Union[str, unicode], context: DeserializationContext
    ) -> None: ...
    def getBodyDecoder(self) -> Any: ...
    def getElementName(self) -> Union[str, unicode]: ...
    def getObject(self) -> Object: ...
    def getRefId(self) -> int: ...
    def onBody(self, body: Object) -> None: ...
    def setRefId(self, id_: int) -> None: ...
    def startElement(
        self,
        name: Union[str, unicode],
        attributes: AttributesMap,
        context: DeserializationContext,
    ) -> None: ...
    def startSubElement(
        self,
        name: Union[str, unicode],
        attributes: AttributesMap,
        context: DeserializationContext,
    ) -> None: ...
    def supportsNestedElements(self) -> bool: ...

class XMLDeserializer(Object):
    def __init__(self, resolver: Optional[ClassNameResolver] = ...) -> None: ...
    def addHandler(self, handler: DeserializationHandler) -> None: ...
    def deserialize(self, *args: Any) -> DeserializationContext: ...
    def deserializeBinary(self, *args: Any) -> DeserializationContext: ...
    def deserializeMultiple(
        self, bytes_: bytearray, count: int
    ) -> List[DeserializationContext]: ...
    def deserializeXML(
        self, streamReader: Reader, topAttributesOnly: bool
    ) -> DeserializationContext: ...
    def getClassNameMap(self) -> ClassNameResolver: ...
    def initDefaults(self) -> XMLDeserializer: ...
    def readRootAttributes(
        self, arg: Any
    ) -> Mapping[Union[str, unicode], Union[str, unicode]]: ...
    def transcodeToXML(
        self, binary: InputStream, serializer: XMLSerializer
    ) -> Union[str, unicode]: ...
