from typing import Any, Iterable, List, Optional, Union

from com.inductiveautomation.ignition.common import QualifiedPath
from com.inductiveautomation.ignition.common.config import (
    BasicProperty,
    Property,
    PropertySet,
    PropertyValue,
)
from com.inductiveautomation.ignition.common.user.schedule import ScheduleAdjustment
from java.lang import Object
from java.util import Date

class User:
    Badge: BasicProperty
    DEFAULT_SCHEDULE_NAME: str
    FirstName: BasicProperty
    Language: BasicProperty
    LastName: BasicProperty
    Notes: BasicProperty
    Password: BasicProperty
    Schedule: BasicProperty
    Username: BasicProperty
    USERNAME_PATTERN: str
    def getContactInfo(self) -> List[ContactInfo]: ...
    def getId(self) -> Any: ...
    def getPath(self) -> QualifiedPath: ...
    def getProfileName(self) -> Union[str, unicode]: ...
    def getRoles(self) -> List[Union[str, unicode]]: ...
    def getScheduleAdjustments(self) -> List[ScheduleAdjustment]: ...

class AuthenticatedUser(User):
    SecurityZones: Property
    def getContactInfo(self) -> List[ContactInfo]: ...
    def getId(self) -> Any: ...
    def getPath(self) -> QualifiedPath: ...
    def getProfileName(self) -> Union[str, unicode]: ...
    def getRoles(self) -> List[Union[str, unicode]]: ...
    def getScheduleAdjustments(self) -> List[ScheduleAdjustment]: ...

class ContactInfo(Object):
    contactType: Union[str, unicode]
    value: Union[str, unicode]
    def __init__(self, *args: Any) -> None: ...
    def getContactType(self) -> Union[str, unicode]: ...
    def getValue(self) -> Union[str, unicode]: ...
    def setContactType(self, contactType: Union[str, unicode]) -> None: ...
    def setValue(self, value: Union[str, unicode]) -> None: ...

class BasicUser(User):
    contactInfo: Optional[List[ContactInfo]]
    id: Any
    profileName: Union[str, unicode]
    roles: List[Union[str, unicode]]
    scheduleAdjustments: List[ScheduleAdjustment]
    def __init__(
        self,
        profileName: Union[str, unicode],
        id_: Any,
        roles: List[Union[str, unicode]],
        contactInfo: Optional[List[ContactInfo]] = ...,
    ) -> None: ...
    def getContactInfo(self) -> List[ContactInfo]: ...
    def getId(self) -> Any: ...
    def getPath(self) -> QualifiedPath: ...
    def getProfileName(self) -> Union[str, unicode]: ...
    def getRoles(self) -> List[Union[str, unicode]]: ...
    def getScheduleAdjustments(self) -> List[ScheduleAdjustment]: ...

class PyUser(User):
    def __init__(self, user: Optional[User] = ...) -> None: ...
    def addContactInfo(self, *args: Any) -> None: ...
    def addRole(self, role: Union[str, unicode]) -> None: ...
    def addRoles(self, roles: List[Union[str, unicode]]) -> None: ...
    def addScheduleAdjustment(
        self, start: Date, end: Date, available: bool, note: Union[str, unicode]
    ) -> None: ...
    def addScheduleAdjustments(
        self, scheduleAdjustments: List[ScheduleAdjustment]
    ) -> None: ...
    def contains(self, prop: Property) -> bool: ...
    def get(self, propertyName: Union[str, unicode, Property]) -> Any: ...
    def getContactInfo(self) -> List[ContactInfo]: ...
    def getCount(self) -> int: ...
    def getId(self) -> Any: ...
    def getOrDefault(self, prop: Property) -> Any: ...
    def getOrElse(self, property: Property, value: Any) -> Any: ...
    def getPath(self) -> QualifiedPath: ...
    def getProfileName(self) -> Union[str, unicode]: ...
    def getProperties(self) -> List[Property]: ...
    def getRoles(self) -> List[Union[str, unicode]]: ...
    def getScheduleAdjustments(self) -> List[ScheduleAdjustment]: ...
    def getValues(self) -> List[PropertyValue]: ...
    def isExtended(self, prop: Property) -> bool: ...
    def isInherited(self, prop: Property) -> bool: ...
    def iterator(self) -> Iterable[Property]: ...
    def merge(self, other: PropertySet, localOnly: bool) -> None: ...
    def remove(self, prop: Property) -> None: ...
    def removeContactInfo(
        self, contactType: Union[str, unicode], value: Union[str, unicode]
    ) -> None: ...
    def removeRole(self, role: Union[str, unicode]) -> None: ...
    def removeScheduleAdjustment(
        self, start: Date, end: Date, available: bool, note: Union[str, unicode]
    ) -> None: ...
    def set(self, *args: Any) -> None: ...
    def setContactInfo(self, contactInfo: List[ContactInfo]) -> None: ...
    def setRoles(self, roles: List[Union[str, unicode]]) -> None: ...
    def setScheduleAdjustments(
        self, scheduleAdjustments: List[ScheduleAdjustment]
    ) -> None: ...

class UserSourceMeta(Object):
    description: Union[str, unicode]
    name: Union[str, unicode]
    type: Union[str, unicode]
    def __init__(
        self,
        name: Union[str, unicode],
        description: Union[str, unicode],
        type_: Union[str, unicode],
    ) -> None: ...
    def getName(self) -> Union[str, unicode]: ...
    def getDescription(self) -> Union[str, unicode]: ...
    def getType(self) -> Union[str, unicode]: ...
