from typing import Iterable, Mapping, Union

import ch.qos.logback.classic
from java.lang import Enum

class Level(Enum):
    def toLevel(self, value: ch.qos.logback.classic.Level) -> Level: ...
    def toLogBack(self) -> ch.qos.logback.classic.Level: ...
    @staticmethod
    def values() -> Iterable[Level]: ...

class LogFilterSettings:
    def addPropertyFilter(
        self, key: Union[str, unicode], value: Union[str, unicode]
    ) -> None: ...
    def clearPropertyLevel(
        self, key: Union[str, unicode], value: Union[str, unicode]
    ) -> None: ...
    def clearPropertyLevels(self) -> None: ...
    def propertyFilterSettings(
        self,
    ) -> Mapping[Union[str, unicode], Mapping[Union[str, unicode], Level]]: ...
    def removePropertyFilter(
        self, key: Union[str, unicode], value: Union[str, unicode]
    ) -> None: ...
    def setLevel(self, logger: Union[str, unicode], level: Level) -> None: ...
    def setPropertyLevel(
        self, key: Union[str, unicode], value: Union[str, unicode], level: Level
    ) -> None: ...
