from typing import Any, Union

from java.lang import Class, Exception, Object

class ClassNameResolver(Object):
    def __init__(self) -> None: ...
    def addAlias(self, clazz: Class, alias: Union[str, unicode]) -> None: ...
    def addDefaults(self) -> None: ...
    def addSearchPath(self, path: Union[str, unicode]) -> None: ...
    def classForName(self, name: Union[str, unicode]) -> Class: ...
    def createBasic(self) -> ClassNameResolver: ...
    def getName(self, clazz: Class) -> Union[str, unicode]: ...

class SerializationException(Exception):
    def __init__(self, *args: Any) -> None: ...
