from typing import Any, List, Mapping, Set, Union

from com.codahale.metrics import Timer
from com.inductiveautomation.ignition.common.script.hints import ScriptFunctionHint
from java.io import OutputStream
from java.lang import Class, Object
from java.util import UUID
from org.python.core import PyObject, PyStringMap, PySystemState

HintsMap = Mapping[Union[str, unicode], List[ScriptFunctionHint]]

class ScriptFunction:
    def invoke(self, *args: Any) -> PyObject: ...

class ScriptManager(Object):
    class ExecutionInfo(Object):
        description: Union[str, unicode]
        startTime: long
        threadId: long

    def __init__(
        self, contextName: Union[str, unicode], pathToExternalLibs: Union[str, unicode]
    ) -> None: ...
    def addGlobalVariable(self, name: Union[str, unicode], value: PyObject) -> None: ...
    def addScriptModule(self, *args: Any) -> None: ...
    def addStaticFields(self, path: Union[str, unicode], clazz: Class) -> None: ...
    def addStdErrStream(self, os: OutputStream) -> None: ...
    def addStdOutStream(self, os: OutputStream) -> None: ...
    @staticmethod
    def asynchInit(pathToExternalLibs: Union[str, unicode, None] = ...) -> None: ...
    def beginCompileTimer(self) -> Timer.Context: ...
    def clearAppModule(self) -> None: ...
    def clearModule(self, moduleName: Union[str, unicode]) -> None: ...
    def clearProjectScriptModules(self) -> None: ...
    def clearThirdPartyModules(self) -> None: ...
    def compileFunction(self, *args: Any) -> ScriptFunction: ...
    def createLocalsMap(self) -> PyStringMap: ...
    @staticmethod
    def createUtf8PySystemState(
        stdOut: OutputStream, stdErr: OutputStream
    ) -> PySystemState: ...
    @staticmethod
    def executingScripts() -> Set[ScriptManager.ExecutionInfo]: ...
    def getCompileTimer(self) -> Timer: ...
    def getExecutionTimer(self) -> Timer: ...
    def getGlobals(self) -> PyStringMap: ...
    def getHintsMap(self) -> HintsMap: ...
    def getModules(self) -> PyStringMap: ...
    def getUUID(self) -> UUID: ...
    @staticmethod
    def interrupt(threadId: long) -> None: ...
    @staticmethod
    def main(*args: Union[str, unicode]) -> None: ...
    def removeStdErrStream(self, os: OutputStream) -> None: ...
    def removeStdOutStream(self, os: OutputStream) -> None: ...
    def runCode(self, *args: Any) -> None: ...
    def runFunction(self, *args: Any) -> PyObject: ...
    def setContextName(self, name: Union[str, unicode]) -> None: ...
    def setPaused(self, paused: bool) -> None: ...
    def shutdown(self) -> None: ...
    def validatePackageName(self, newName: Union[str, unicode]) -> None: ...
