from typing import List, Mapping, Optional, Union

from com.inductiveautomation.ignition.common.licensing import LicenseState
from com.inductiveautomation.ignition.common.model import Version
from com.inductiveautomation.ignition.common.util import Platform
from java.lang import Object

class ModuleInfo(Object):
    class Builder(Object):
        def __init__(self) -> None: ...
        def addDependency(
            self, dependency: ModuleInfo.ModuleDependency
        ) -> ModuleInfo.Builder: ...
        def build(self) -> ModuleInfo: ...
        def setDependencies(
            self, dependencies: List[ModuleInfo.ModuleDependency]
        ) -> ModuleInfo.Builder: ...
        def setDescription(
            self, description: Union[str, unicode]
        ) -> ModuleInfo.Builder: ...
        def setExports(
            self, exports: List[ModuleInfo.JarInfo]
        ) -> ModuleInfo.Builder: ...
        def setHooks(
            self, hooks: Mapping[int, Union[str, unicode]]
        ) -> ModuleInfo.Builder: ...
        def setId(self, id_: Union[str, unicode]) -> ModuleInfo.Builder: ...
        def setJars(self, jars: List[ModuleInfo.JarInfo]) -> ModuleInfo.Builder: ...
        def setLicenseFile(
            self, licenseFilename: Union[str, unicode]
        ) -> ModuleInfo.Builder: ...
        def setName(self, name: Union[str, unicode]) -> ModuleInfo.Builder: ...
        def setRequire(
            self, require: List[ModuleInfo.LibraryInfo]
        ) -> ModuleInfo.Builder: ...
        def setRequiredFrameworkVersion(
            self, requiredFrameworkVersion: int
        ) -> ModuleInfo.Builder: ...
        def setRequiredIgnitionVersion(
            self, requiredIgnitionVersion: Version
        ) -> ModuleInfo.Builder: ...
        def setSelfSigned(self, selfSigned: bool) -> ModuleInfo.Builder: ...
        def setVendor(
            self, id_: int, name: Union[str, unicode], contactInfo: Union[str, unicode]
        ) -> ModuleInfo.Builder: ...
        def setVersion(self, version: Version) -> ModuleInfo.Builder: ...

    class JarInfo(Object):
        def __init__(
            self,
            scope: int,
            path: Union[str, unicode],
            requiredOs: Union[str, unicode] = ...,
            requiredArch: Union[str, unicode] = ...,
        ) -> None: ...
        def getPath(self) -> Union[str, unicode]: ...
        def getRequiredArch(self) -> Union[str, unicode]: ...
        def getRequiredOS(self) -> Union[str, unicode]: ...
        def getScope(self) -> int: ...
        def isNativeLib(self) -> bool: ...
        def isRequiredArchitecture(self, arch: Platform.Architecture) -> bool: ...
        def isRequiredOS(self, os: Platform.OperatingSystem) -> bool: ...

    class LibraryInfo(Object):
        def getName(self) -> Union[str, unicode]: ...
        def getScope(self) -> int: ...
        def setName(self, name: Union[str, unicode]) -> None: ...
        def setScope(self, scope: int) -> None: ...

    class ModuleDependency(Object):
        def getModuleId(self) -> Union[str, unicode]: ...
        def getScope(self) -> int: ...
        def getVersion(self) -> Version: ...

    def getCrc(self) -> long: ...
    def getDependencies(
        self, scope: Optional[int] = ...
    ) -> List[ModuleInfo.ModuleDependency]: ...
    def getDescription(self) -> Union[str, unicode]: ...
    def getDocumentationRoot(self) -> Union[str, unicode]: ...
    def getExports(self) -> List[ModuleInfo.JarInfo]: ...
    def getHooks(self) -> Mapping[int, Union[str, unicode]]: ...
    def getId(self) -> Union[str, unicode]: ...
    def getInstallPath(self) -> Union[str, unicode]: ...
    def getJars(self) -> List[ModuleInfo.JarInfo]: ...
    def getLibsRequired(self) -> List[ModuleInfo.LibraryInfo]: ...
    def getLicenseFile(self) -> Union[str, unicode]: ...
    def getLicenseState(self) -> LicenseState: ...
    def getName(self) -> Union[str, unicode]: ...
    def getRequiredFrameworkVersion(self) -> int: ...
    def getRequiredIgnitionVersion(self) -> Version: ...
    def getVendorContactInfo(self) -> Union[str, unicode]: ...
    def getVendorId(self) -> int: ...
    def getVendorName(self) -> Union[str, unicode]: ...
    def getVersion(self) -> Version: ...
    def isFree(self) -> bool: ...
    def isMakerEditionCompatible(self) -> bool: ...
    def isSelfSigned(self) -> bool: ...
    def isTrialMode(self) -> bool: ...
    @staticmethod
    def newBuilder() -> ModuleInfo.Builder: ...
    def setCrc(self, crc: long) -> None: ...
    def setFree(self) -> None: ...
    def setInstallPath(self, installPath: Union[str, unicode]) -> None: ...
    def setLicenseState(self, newState: LicenseState) -> None: ...
    def setMakerEditionCompatible(self) -> None: ...
    def setSelfSigned(self) -> None: ...
    def setVendorInfo(
        self,
        vendorId: int,
        vendorName: Union[str, unicode],
        vendorContactInfo: Union[str, unicode],
    ) -> None: ...
    @staticmethod
    def setDependencyOrder(
        list_: List[ModuleInfo], scope: int, reverse: bool
    ) -> List[ModuleInfo]: ...
    def toXML(self) -> Union[str, unicode]: ...
