from typing import Any, Union

from java.lang import Object

class EventBus(Object):
    def __init__(self, *args: Any) -> None: ...
    def identifier(self) -> Union[str, unicode]: ...
    def post(self, event: Object) -> None: ...
    def register(self, obj: Object) -> None: ...
    def unregister(self, obj: Object) -> None: ...
