from typing import Any, Union

from java.lang import Class

class TypeBuilder:
    def getBase(self) -> Class: ...
    def getDict(self, var1: Any) -> Any: ...
    def getDoc(self) -> Union[str, unicode]: ...
    def getIsBaseType(self) -> bool: ...
    def getName(self) -> Union[str, unicode]: ...
    def getTypeClass(self) -> Class: ...
