from typing import List, Union

from com.inductiveautomation.ignition.common.user import User
from com.palantir.ptoss.cinch.core import DefaultBindableModel

class RosterModel(DefaultBindableModel):
    def __init__(self) -> None: ...
    def getDescription(self) -> Union[str, unicode]: ...
    def getName(self) -> Union[str, unicode]: ...
    def getUsers(self) -> List[User]: ...
    def set(self, that: RosterModel) -> None: ...
    def setDescription(self, description: Union[str, unicode]) -> None: ...
    def setName(self, name: Union[str, unicode]) -> None: ...
    def setUsers(self, users: List[User]) -> None: ...
