from typing import List, Union

from java.lang import Enum

class SpreadsheetVersion(Enum):
    def getLastColumnIndex(self) -> int: ...
    def getLastColumnName(self) -> Union[str, unicode]: ...
    def getLastRowIndex(self) -> int: ...
    def getMaxCellStyles(self) -> int: ...
    def getMaxColumns(self) -> int: ...
    def getMaxConditionalFormats(self) -> int: ...
    def getMaxFunctionArgs(self) -> int: ...
    def getMaxRows(self) -> int: ...
    def getMaxTextLength(self) -> int: ...
    @staticmethod
    def getValueOf(name: Union[str, unicode]) -> SpreadsheetVersion: ...
    @staticmethod
    def values() -> List[SpreadsheetVersion]: ...
