from typing import Any, Iterator, List

from com.inductiveautomation.ignition.common import Dataset
from com.inductiveautomation.ignition.common.alarming import AlarmEvent, PyAlarmEvent
from dev.coatl.helper.types import AnyStr
from java.util import ArrayList

class AlarmQueryResult:
    def getAssociatedData(self, uuid: AnyStr) -> Dataset: ...
    def getDataset(self) -> Dataset: ...
    def getEvent(self, uuid: AnyStr) -> AlarmEvent: ...

class AlarmQueryResultImpl(AlarmQueryResult, ArrayList):
    def __init__(self, *args: Any) -> None: ...
    @staticmethod
    def buildFrom(results: List[AlarmQueryResult]) -> AlarmQueryResult: ...
    def getAssociatedData(self, uuid: AnyStr) -> Dataset: ...
    def getDataset(self) -> Dataset: ...
    def getEvent(self, uuid: AnyStr) -> AlarmEvent: ...
    def __iter__(self) -> Iterator[PyAlarmEvent]: ...
