from typing import Any, Union

from java.lang import Object
from org.python.core import PyObject

class SerialScriptModule(Object):
    class PortManager:
        def __init__(self, *args: Any) -> None: ...
        def __enter__(self) -> None: ...
        def __exit__(
            self, exc_type: object, exc_val: object, exc_tb: object
        ) -> None: ...

    class SerialConfigurator:
        def setBitRate(self, value: int) -> SerialScriptModule.SerialConfigurator: ...
        def setDataBits(self, value: int) -> SerialScriptModule.SerialConfigurator: ...
        def setFlowControl(
            self, value: bool
        ) -> SerialScriptModule.SerialConfigurator: ...
        def setHandshake(self, value: int) -> SerialScriptModule.SerialConfigurator: ...
        def setHardwareFlowControl(
            self, value: int
        ) -> SerialScriptModule.SerialConfigurator: ...
        def setParity(self, value: int) -> SerialScriptModule.SerialConfigurator: ...
        def setStopBits(self, value: int) -> SerialScriptModule.SerialConfigurator: ...

    class SerialPortWrapper(PyObject):
        def __init__(self, port: Union[str, unicode], serialPort: Any) -> None: ...
        def readBytes(
            self, port: Union[str, unicode], numberOfBytes: int, timeout: int = ...
        ) -> bytearray: ...
        def readBytesAsString(
            self,
            port: Union[str, unicode],
            numberOfBytes: int,
            timeout: int = ...,
            encoding: Union[str, unicode] = ...,
        ) -> Union[str, unicode]: ...
        def readLine(
            self,
            port: Union[str, unicode],
            timeout: int = ...,
            encoding: Union[str, unicode] = ...,
            crlfRequired: bool = ...,
        ) -> Union[str, unicode]: ...
        def readUntil(
            self,
            port: Union[str, unicode],
            delimiter: Union[str, unicode],
            includeDelimiter: bool,
            timeout: int = ...,
        ) -> Union[str, unicode]: ...
        def sendBreak(self, port: Union[str, unicode], millis: long) -> None: ...
        def write(
            self,
            port: Union[str, unicode],
            toWrite: bytearray,
            encoding: Union[str, unicode] = ...,
        ) -> None: ...
        def writeBytes(
            self, port: Union[str, unicode], toWrite: bytearray, timeout: int = ...
        ) -> None: ...

    def __init__(self) -> None: ...
    @staticmethod
    def setTrialExpired(trialExpired: bool) -> None: ...
