from typing import Any, Optional, Set, Union

from java.lang import Object, Throwable
from java.util import Locale

class ExceptionContext(Object):
    def __init__(self, throwable: Throwable) -> None: ...
    def addMessage(self, pattern: Union[str, unicode], *args: Any) -> None: ...
    def getKeys(self) -> Set[Union[str, unicode]]: ...
    def getLocalizedMessage(self) -> Union[str, unicode]: ...
    def getMessage(
        self, locale: Optional[Locale] = ..., separator: Union[str, unicode, None] = ...
    ) -> Union[str, unicode]: ...
    def getThrowable(self) -> Throwable: ...
    def getValue(self, key: Union[str, unicode]) -> None: ...
    def setValue(self, key: Union[str, unicode], value: Object) -> None: ...
