from typing import Iterable, Union

from com.palantir.ptoss.cinch.core import DefaultBindableModel
from java.lang import Enum

class ScheduleModel(DefaultBindableModel):
    class DayOfWeek(Enum):
        @staticmethod
        def values() -> Iterable[ScheduleModel.DayOfWeek]: ...

    def __init__(self) -> None: ...
    def deselectDayOfWeek(self, day: ScheduleModel.DayOfWeek) -> None: ...
    def getEveryHour(self) -> Union[str, unicode]: ...
    def getHour(self) -> Union[str, unicode]: ...
    def getMinute(self) -> Union[str, unicode]: ...
    def getSelectedDays(self) -> Union[str, unicode]: ...
    def isAlldays(self) -> bool: ...
    def isDaySelected(self, day: ScheduleModel.DayOfWeek) -> bool: ...
    def isEveryHourEnabled(self) -> bool: ...
    def isEveryMinuteEnabled(self) -> bool: ...
    def isHourEnabled(self) -> bool: ...
    def isMinuteEnabled(self) -> bool: ...
    def selectDayOfWeek(self, day: ScheduleModel.DayOfWeek) -> None: ...
    def setAllDays(self, allDays: bool) -> None: ...
    def setEveryHour(self, everyHour: Union[str, unicode]) -> None: ...
    def setHour(self, hour: Union[str, unicode]) -> None: ...
    def setHourEnabled(self, hourEnabled: bool) -> None: ...
    def setMinute(self, minute: Union[str, unicode]) -> None: ...
    def setMinuteEnabled(self, minuteEnabled: bool) -> None: ...
    def setSelectedDays(self, selectedDays: Union[str, unicode]) -> None: ...
    def toCronString(self) -> Union[str, unicode]: ...
