from typing import Any, Dict, Union

from com.inductiveautomation.ignition.common import BasicDataset

def addDevice(
    deviceType: Union[str, unicode],
    deviceName: Union[str, unicode],
    deviceProps: Dict[Union[str, unicode], Any],
    description: Union[str, unicode, None] = ...,
) -> None: ...
def getDeviceHostname(deviceName: Union[str, unicode]) -> Union[str, unicode]: ...
def listDevices() -> BasicDataset: ...
def refreshBrowse(deviceName: Union[str, unicode]) -> None: ...
def removeDevice(deviceName: Union[str, unicode]) -> None: ...
def restart(deviceName: Union[str, unicode]) -> None: ...
def setDeviceEnabled(deviceName: Union[str, unicode], enabled: bool) -> None: ...
def setDeviceHostname(
    deviceName: Union[str, unicode], hostname: Union[str, unicode]
) -> None: ...
