from typing import Any, Callable, List, Optional, Tuple, Union

from com.inductiveautomation.factorypmi.application import FPMIWindow
from com.inductiveautomation.factorypmi.application.script.builtin import (
    WindowUtilities,
)
from java.awt import Color
from java.org.jdesktop.core.animation.timing import Animator
from java.util import EventObject
from javax.swing import JComponent, JFrame, JPopupMenu

ACCL_NONE: int
ACCL_CONSTANT: int
ACCL_FAST_TO_SLOW: int
ACCL_SLOW_TO_FAST: int
ACCL_EASE: int
COORD_DESIGNER: int
COORD_SCREEN: int

def chooseColor(
    initialColor: Color, dialogTitle: Union[str, unicode] = ...
) -> Color: ...
def closeDesktop(handle: Union[str, unicode]) -> None: ...
def color(*args: Any) -> Color: ...
def confirm(
    message: Union[str, unicode],
    title: Union[str, unicode] = ...,
    allowCancel: bool = ...,
) -> Optional[bool]: ...
def convertPointToScreen(x: int, y: int, event: EventObject) -> Tuple[int, int]: ...
def createPopupMenu(
    itemNames: List[Union[str, unicode]], itemFunctions: List[Callable[..., Any]]
) -> JPopupMenu: ...
def desktop(handle: Union[str, unicode]) -> WindowUtilities: ...
def errorBox(
    message: Union[str, unicode], title: Union[str, unicode] = ...
) -> None: ...
def findWindow(path: Union[str, unicode]) -> List[FPMIWindow]: ...
def getCurrentDesktop() -> Union[str, unicode]: ...
def getDesktopHandles() -> List[Union[str, unicode]]: ...
def getOpenedWindowNames() -> Tuple[Union[str, unicode], ...]: ...
def getOpenedWindows() -> Tuple[FPMIWindow, ...]: ...
def getParentWindow(event: EventObject) -> FPMIWindow: ...
def getQuality(component: JComponent, propertyName: Union[str, unicode]) -> int: ...
def getScreenIndex() -> int: ...
def getScreens() -> List[Tuple[Union[str, unicode], int, int]]: ...
def getSibling(event: EventObject, name: Union[str, unicode]) -> FPMIWindow: ...
def getWindow(name: Union[str, unicode]) -> FPMIWindow: ...
def getWindowNames() -> Tuple[Union[str, unicode], ...]: ...
def inputBox(
    message: Union[str, unicode], defaultText: Union[str, unicode] = ...
) -> Union[str, unicode, None]: ...
def isTouchscreenModeEnabled() -> bool: ...
def messageBox(
    message: Union[str, unicode], title: Union[str, unicode] = ...
) -> None: ...
def openDesktop(
    screen: int = ...,
    handle: Union[str, unicode, None] = ...,
    title: Union[str, unicode, None] = ...,
    width: Optional[int] = ...,
    height: Optional[int] = ...,
    x: int = ...,
    y: int = ...,
    windows: Optional[List[Union[str, unicode]]] = ...,
) -> JFrame: ...
def openDiagnostics() -> None: ...
def passwordBox(
    message: Union[str, unicode],
    title: Union[str, unicode] = ...,
    echoChar: Union[str, unicode] = ...,
) -> Union[str, unicode, None]: ...
def setScreenIndex(index: int) -> None: ...
def setTouchscreenModeEnabled(enabled: bool) -> None: ...
def showNumericKeypad(
    initialValue: Union[float, int, long],
    fontSize: Optional[int] = ...,
    usePasswordMode: bool = ...,
) -> Union[float, int, long]: ...
def showTouchscreenKeyboard(
    initialText: Union[str, unicode],
    fontSize: Optional[int] = ...,
    passwordMode: bool = ...,
) -> Union[str, unicode]: ...
def transform(
    component: JComponent,
    newX: Optional[int] = ...,
    newY: Optional[int] = ...,
    newWidth: Optional[int] = ...,
    newHeight: Optional[int] = ...,
    duration: int = ...,
    callback: Optional[Callable[..., Any]] = ...,
    framesPerSecond: int = ...,
    acceleration: Optional[int] = ...,
    coordSpace: Optional[int] = ...,
) -> Animator: ...
def warningBox(
    message: Union[str, unicode], title: Union[str, unicode] = ...
) -> None: ...
