from typing import Dict, List, Union

from com.inductiveautomation.ignition.alarming.common.rosters import RosterModel
from com.inductiveautomation.ignition.common.user import PyUser

def addUsers(rosterName: Union[str, unicode], users: List[PyUser]) -> None: ...
def createRoster(
    name: Union[str, unicode], description: Union[str, unicode, None]
) -> None: ...
def deleteRoster(rosterName: Union[str, unicode]) -> None: ...
def getRoster(name: Union[str, unicode]) -> RosterModel: ...
def getRosterNames() -> List[Union[str, unicode]]: ...
def getRosters() -> Dict[Union[str, unicode], List[Union[str, unicode]]]: ...
def removeUsers(rosterName: Union[str, unicode], users: List[PyUser]) -> None: ...
