from typing import List, Union

from com.inductiveautomation.ignition.common import BasicDataset

def getAccounts() -> List[Union[str, unicode]]: ...
def getAccountsDataset() -> BasicDataset: ...
def getPhoneNumbers(accountName: Union[str, unicode]) -> List[Union[str, unicode]]: ...
def getPhoneNumbersDataset(accountName: Union[str, unicode]) -> BasicDataset: ...
def sendSms(
    accountName: Union[str, unicode],
    fromNumber: Union[str, unicode],
    toNumber: Union[str, unicode],
    message: Union[str, unicode],
) -> None: ...
