from typing import Any, List, Optional, Union

from com.inductiveautomation.ignition.common.config import Property
from com.inductiveautomation.ignition.common.tags.model import TagPath
from java.lang import Object

class AbstractTagPath(Object, TagPath):
    def __init__(self) -> None: ...
    @staticmethod
    def compareNullLow(c1: Property, c2: Property) -> int: ...
    def getChildPath(self, nextId: Union[str, unicode]) -> TagPath: ...
    def getItemName(self) -> Union[str, unicode]: ...
    def getParentPath(self) -> TagPath: ...
    def getProperty(self) -> Property: ...
    def getSource(self) -> Union[str, unicode]: ...
    def toStringFull(self) -> Union[str, unicode]: ...
    def toStringPartial(self) -> Union[str, unicode]: ...

class BasicTagPath(AbstractTagPath):
    def __init__(
        self,
        source: Union[str, unicode],
        pathParts: Optional[List[Union[str, unicode]]] = ...,
        prop: Optional[Property] = ...,
    ) -> None: ...
    @staticmethod
    def append(root: TagPath, arg: Union[str, unicode, TagPath]) -> TagPath: ...
    @staticmethod
    def copy(path: TagPath) -> BasicTagPath: ...
    @staticmethod
    def renameParentFolder(path: TagPath, newParent: TagPath) -> BasicTagPath: ...
    @staticmethod
    def subPath(path: TagPath, *args: Any) -> BasicTagPath: ...

class PropertyAlteredTagPath(AbstractTagPath):
    def __init__(self, path: TagPath, prop: Property) -> None: ...

class SourceAlteredTagPath(AbstractTagPath):
    def __init__(self, path: TagPath, source: Union[str, unicode]) -> None: ...
