from typing import Mapping, Union

class ScriptFunctionHint:
    def getAutocompleteText(self) -> Union[str, unicode]: ...
    def getMethodDescription(self) -> Union[str, unicode]: ...
    def getMethodSignature(self) -> Union[str, unicode]: ...
    def getParameterDescriptions(
        self,
    ) -> Mapping[Union[str, unicode], Union[str, unicode]]: ...
    def getReturnValueDescription(self) -> Union[str, unicode]: ...
