from typing import Any, Iterator, Union

from com.inductiveautomation.ignition.common import QualifiedPath, StringPath
from com.inductiveautomation.ignition.common.config import BasicPropertySet
from java.lang import Object
from java.util import UUID
from org.python.core import PyObject

class AlarmEvent:
    def acknowledge(self, ackData: EventData) -> None: ...
    def active(self, activeData: EventData) -> None: ...
    def clear(self, clearData: EventData) -> None: ...
    def getAckData(self) -> EventData: ...
    def getActiveData(self) -> EventData: ...
    def getClearedData(self) -> EventData: ...
    def getDisplayPath(self) -> StringPath: ...
    def getDisplayPathOrSource(self) -> Union[str, unicode]: ...
    def getId(self) -> UUID: ...
    def getLabel(self) -> Union[str, unicode]: ...
    def getLastEventState(self) -> Any: ...
    def getName(self) -> Union[str, unicode]: ...
    def getNotes(self) -> Union[str, unicode]: ...
    def getPriority(self) -> Any: ...
    def getSource(self) -> QualifiedPath: ...
    def getState(self) -> Any: ...
    def isAcked(self) -> bool: ...
    def isCleared(self) -> bool: ...
    def isShelved(self) -> bool: ...
    def iterator(self) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...

class EventData(BasicPropertySet):
    def __init__(self, *args: Any) -> None: ...
    def getTimeStamp(self) -> long: ...

class PyAlarmEvent(AlarmEvent):
    def acknowledge(self, ackData: EventData) -> None: ...
    def active(self, activeData: EventData) -> None: ...
    def clear(self, clearData: EventData) -> None: ...
    def contains(self, property: Union[str, unicode]) -> bool: ...
    def get(self, property: Union[str, unicode]) -> Object: ...
    def getAckData(self) -> EventData: ...
    def getActiveData(self) -> EventData: ...
    def getClearedData(self) -> EventData: ...
    def getDisplayPath(self) -> StringPath: ...
    def getDisplayPathOrSource(self) -> Union[str, unicode]: ...
    def getId(self) -> UUID: ...
    def getLabel(self) -> Union[str, unicode]: ...
    def getLastEventState(self) -> Any: ...
    def getName(self) -> Union[str, unicode]: ...
    def getNotes(self) -> Union[str, unicode]: ...
    def getOrDefault(self, property: Union[str, unicode]) -> Object: ...
    def getOrElse(
        self, property: Union[str, unicode], defaultValue: Object
    ) -> Object: ...
    def getPriority(self) -> Any: ...
    def getSource(self) -> QualifiedPath: ...
    def getState(self) -> Any: ...
    def isAcked(self) -> bool: ...
    def isCleared(self) -> bool: ...
    def isShelved(self) -> bool: ...
    def set(self, property: Union[str, unicode], value: Object) -> None: ...
    def setGlobal(self, property: Union[str, unicode], value: Object) -> None: ...
    def sourceEvent(self) -> AlarmEvent: ...
    def __iter__(self) -> Iterator[Any]: ...

class PyAlarmEventImpl(PyAlarmEvent, PyObject):
    def __init__(self, event: AlarmEvent) -> None: ...
    def contains(self, property: Union[str, unicode]) -> bool: ...
    def get(self, property: Union[str, unicode]) -> Object: ...
    def getOrDefault(self, property: Union[str, unicode]) -> Object: ...
    def getOrElse(
        self, property: Union[str, unicode], defaultValue: Object
    ) -> Object: ...
    def set(self, property: Union[str, unicode], value: Object) -> None: ...
    def setGlobal(self, property: Union[str, unicode], value: Object) -> None: ...
    def sourceEvent(self) -> AlarmEvent: ...
