from typing import Any, List, Set, Union

from org.apache.poi.hpsf import ClassID

class Entry:
    def delete(self) -> bool: ...
    def getName(self) -> Union[str, unicode]: ...
    def getParent(self) -> DirectoryEntry: ...
    def isDirectoryEntry(self) -> bool: ...
    def isDocumentEntry(self) -> bool: ...
    def renameTo(self, newName: Union[str, unicode]) -> None: ...

class DirectoryEntry(Entry):
    def createDirectory(self, name: Union[str, unicode]) -> DirectoryEntry: ...
    def createDocument(self, *args: Any) -> None: ...
    def delete(self) -> bool: ...
    def getEntries(self) -> List[Entry]: ...
    def getEntry(self, name: Union[str, unicode]) -> Entry: ...
    def getEntryCount(self) -> int: ...
    def getEntryNames(self) -> Set[Union[str, unicode]]: ...
    def getName(self) -> Union[str, unicode]: ...
    def getParent(self) -> DirectoryEntry: ...
    def getStorageClsid(self) -> ClassID: ...
    def hasEntry(self, name: Union[str, unicode]) -> bool: ...
    def isDirectoryEntry(self) -> bool: ...
    def isDocumentEntry(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def renameTo(self, newName: Union[str, unicode]) -> None: ...
    def setStorageClsid(self, clsidStorage: ClassID) -> None: ...
