name: pre-commit-autoupdate

on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

jobs:
  pre-commit-autoupdate:
    uses: coatl-dev/workflows/.github/workflows/pre-commit-autoupdate.yml@v4
    with:
      skip-repos: 'flake8'
    secrets:
      gh-token: ${{ secrets.COATL_BOT_GH_TOKEN }}
      gpg-sign-passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
      gpg-sign-private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}
