from typing import Any, Dict, List, Optional, Tuple, Union

from com.inductiveautomation.ignition.common import BasicDataset, Dataset
from com.inductiveautomation.ignition.common.model.values import (
    QualifiedValue,
    QualityCode,
)
from com.inductiveautomation.ignition.common.opc import BrowseElementType
from com.inductiveautomation.ignition.common.script.abc import AbstractJythonSequence
from com.inductiveautomation.ignition.common.script.message import Request
from java.io import OutputStream, Writer
from java.lang import Class
from java.lang import Exception as JavaException
from java.lang import Object
from java.util import Locale
from org.json import JSONObject
from org.python.core import PyFunction, PyList, PyObject, PySequence
from org.slf4j import Logger

class AbstractOPCUtilities(Object):
    class PyOPCTag(PyObject):
        displayName: Union[str, unicode]
        elementType: BrowseElementType
        nodeId: Union[str, unicode]
        serverName: Union[str, unicode]
        def __init__(
            self,
            serverName: Union[str, unicode],
            nodeId: Union[str, unicode],
            displayName: Union[str, unicode],
            elementType: BrowseElementType,
        ) -> None: ...
        def __findattr_ex__(self, name: Union[str, unicode]) -> PyObject: ...
        def getDisplayName(self) -> Union[str, unicode]: ...
        def getElementType(self) -> BrowseElementType: ...
        def getNodeId(self) -> Union[str, unicode]: ...
        def getServerName(self) -> Union[str, unicode]: ...

    def browseServer(
        self, opcServer: Union[str, unicode], nodeId: Union[str, unicode]
    ) -> List[AbstractOPCUtilities.PyOPCTag]: ...
    def getServers(
        self, *args: PyObject, **kwargs: Union[str, unicode]
    ) -> List[Union[str, unicode]]: ...
    def getServerState(self, opcServer: Union[str, unicode]) -> Union[str, unicode]: ...
    def isServerEnabled(self, serverName: Union[str, unicode]) -> bool: ...
    def readValue(
        self, opcServer: Union[str, unicode], itemPath: Union[str, unicode]
    ) -> QualifiedValue: ...
    def readValues(
        self, opcServer: Union[str, unicode], itemPaths: List[Union[str, unicode]]
    ) -> QualifiedValue: ...
    def setServerEnabled(
        self, serverName: Union[str, unicode], enabled: bool
    ) -> None: ...
    def writeValue(
        self, *args: PyObject, **kwargs: Union[str, unicode]
    ) -> QualityCode: ...
    def writeValues(
        self, *args: PyObject, **kwargs: Union[str, unicode]
    ) -> List[QualityCode]: ...

class DatasetUtilities(Object):
    class PyDataSet(Dataset, AbstractJythonSequence):
        def __init__(self, ds: Optional[Dataset] = ...) -> None: ...
        def getColumnCount(self) -> int: ...
        def getColumnIndex(self, colName: Union[str, unicode]) -> int: ...
        def getColumnName(self, col: int) -> Union[str, unicode]: ...
        def getColumnNames(self) -> List[Union[str, unicode]]: ...
        def getColumnType(self, col: int) -> Class: ...
        def getColumnTypes(self) -> List[Class]: ...
        def getPrimitiveValueAt(self, row: int, col: int) -> float: ...
        def getQualityAt(self, row: int, col: int) -> QualityCode: ...
        def getRowCount(self) -> int: ...
        def getUnderlyingDataset(self) -> Dataset: ...
        def getValueAt(self, row: int, col: Union[int, str, unicode]) -> Any: ...
        def setData(self, data: Dataset) -> None: ...
        def __add__(self, other: PyObject) -> PyObject: ...

    @staticmethod
    def addColumn(ds: Dataset, *args: Any) -> Dataset: ...
    @staticmethod
    def addRow(ds: Dataset, *args: Any) -> Dataset: ...
    @staticmethod
    def addRows(ds: Dataset, *args: Any) -> Dataset: ...
    @staticmethod
    def appendDataset(ds1: Dataset, ds2: Dataset) -> Dataset: ...
    @staticmethod
    def clearDataset(ds: Dataset) -> Dataset: ...
    @staticmethod
    def dataSetToExcel(
        headerRow: bool, datasets: List[Object]
    ) -> Union[str, unicode]: ...
    @staticmethod
    def dataSetToExcelBytes(
        headerRow: bool,
        objects: List[Object],
        nullsEmpty: bool,
        sheetNames: List[Union[str, unicode]],
    ) -> bytearray: ...
    @staticmethod
    def dataSetToExcelStreaming(
        headerRow: bool, objects: List[Object], out: OutputStream, nullsEmpty: bool
    ) -> None: ...
    @staticmethod
    def dataSetToHTML(
        headerRow: bool, ds: Dataset, title: Union[str, unicode]
    ) -> Union[str, unicode]: ...
    @staticmethod
    def dataSetToHTMLStreaming(
        headerRow: bool, ds: Dataset, title: Union[str, unicode], fw: Writer
    ) -> None: ...
    @staticmethod
    def deleteRow(ds: Dataset, row: int) -> Dataset: ...
    @staticmethod
    def deleteRows(ds: Dataset, rows: List[int]) -> Dataset: ...
    @staticmethod
    def filterColumns(dataset: Dataset, columns: PySequence) -> Dataset: ...
    @staticmethod
    def formatDates(
        dataset: Dataset, format: Union[str, unicode], locale: Locale = ...
    ) -> Dataset: ...
    @staticmethod
    def fromCSV(csv: Union[str, unicode]) -> Dataset: ...
    @staticmethod
    def fromCSVJava(csv: Union[str, unicode]) -> Dataset: ...
    @staticmethod
    def getColumnHeaders(ds: Dataset) -> PyList: ...
    @staticmethod
    def insertColumn(ds: Dataset, *args: Any) -> Dataset: ...
    @staticmethod
    def insertRow(ds: Dataset, *args: Any) -> Dataset: ...
    @staticmethod
    def setValue(
        ds: Dataset,
        row: int,
        col: Union[int, str, unicode],
        value: Union[Object, PyObject],
    ) -> Dataset: ...
    @staticmethod
    def sort(
        ds: Dataset,
        keyColumn: Union[int, str, unicode],
        ascending: Optional[bool] = ...,
        naturalOrdering: Optional[bool] = ...,
    ) -> BasicDataset: ...
    @staticmethod
    def toCSV(
        *args: PyObject, **kwargs: Union[str, unicode]
    ) -> Union[str, unicode]: ...
    @staticmethod
    def toCSVJava(
        ds: Dataset, showHeaders: bool, forExport: bool, localized: bool = ...
    ) -> Union[str, unicode]: ...
    @staticmethod
    def toCSVJavaStreaming(
        ds: Dataset, showHeaders: bool, forExport: bool, sw: Writer, localized: bool
    ) -> None: ...
    @staticmethod
    def toDataSet(*args: Any) -> Dataset: ...
    @staticmethod
    def toExcel(*args: PyObject, **kwargs: Union[str, unicode]) -> bytearray: ...
    @staticmethod
    def toJSONObject(data: Dataset) -> JSONObject: ...
    @staticmethod
    def toPyDataSet(dataset: Dataset) -> PyDataSet: ...
    @staticmethod
    def updateRow(
        ds: Dataset, row: int, changes: Dict[Union[str, unicode], Any]
    ) -> Dataset: ...

class SProcCall(Object):
    class SProcArg(Object):
        outParam: bool
        inParam: bool
        paramType: int
        value: Object
        def getParamType(self) -> int: ...
        def getValue(self) -> Any: ...
        def isInParam(self) -> bool: ...
        def isOutParam(self) -> bool: ...
        def setParamType(self, paramType: int) -> None: ...
        def setValue(self, value: Object) -> None: ...

    class SProcArgKey(Object):
        index: int
        name: Union[str, unicode]
        def getParamIndex(self) -> int: ...
        def getParamName(self) -> Union[str, unicode]: ...
        def isNamedParam(self) -> bool: ...

    callFinished: bool
    datasource: Union[str, unicode]
    params: Dict[SProcCall.SProcArgKey, SProcCall.SProcArg]
    procedureName: Union[str, unicode]
    resultset: Dataset
    returnParam: SProcCall.SProcArg
    skipAudit: bool
    txId: Union[str, unicode]
    updateCount: int
    def getDataSource(self) -> Union[str, unicode]: ...
    def getOutParamValue(self, param: Union[int, str, unicode]) -> Any: ...
    def getProcedureName(self) -> Union[str, unicode]: ...
    def getResultSet(self) -> BasicDataset: ...
    def getReturnValue(self) -> Any: ...
    def getTxId(self) -> Union[str, unicode]: ...
    def getUpdateCount(self) -> int: ...
    def isSkipAudit(self) -> bool: ...
    def registerInParam(
        self, param: Union[int, str, unicode], typeCode: int, value: Any
    ) -> None: ...
    def registerOutParam(
        self, param: Union[int, str, unicode], typeCode: int
    ) -> None: ...
    def registerReturnParam(self, typeCode: int) -> None: ...
    def setSkipAudit(self, skipAudit: bool) -> None: ...
    def setTxId(self, txId: Union[str, unicode]) -> None: ...

class SystemUtilities(Object):
    class RequestImpl(Object, Request):
        timeout: int
        def __init__(self, timeout: int) -> None: ...
        def cancel(self) -> None: ...
        def checkTimeout(self) -> None: ...
        def finishExceptionally(self, e: JavaException) -> None: ...
        def finishSuccessfully(self, value: Object) -> None: ...
        def get(self) -> Object: ...
        def getError(self) -> JavaException: ...
        def getLongId(self) -> long: ...
        def onError(self, func: PyFunction) -> None: ...
        def onSuccess(self, func: PyFunction) -> None: ...

    @staticmethod
    def logger(loggerName: Union[str, unicode]) -> Logger: ...
    @staticmethod
    def parseTranslateArguments(
        *args: PyObject, **kwargs: Union[str, unicode]
    ) -> Tuple[Union[str, unicode], Union[str, unicode], bool]: ...
